name: Deploy para Firebase Hosting com Service Account

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Autenticar com chave de serviço
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > credentials.json
          firebase login:ci --token "$(cat credentials.json | jq -r '.token')" || echo "Autenticação manual não necessária"
          firebase deploy --only hosting --project "$(cat credentials.json | jq -r '.project_id')" --token "$(cat credentials.json | jq -r '.token')"
